import { Html, OrbitControls, PerspectiveCamera, useProgress } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'
import Head from 'next/head'
import { Suspense, useState } from 'react'
import Model from '../components/Model'
import { motion } from 'framer-motion'
import { AiOutlineInfoCircle } from "react-icons/ai";

function Scene() {
  return (
    <>
      {/* Accessoires */}
      <PerspectiveCamera makeDefault fov={50} position={[0, 1, 10]} />
      <OrbitControls />
      <ambientLight intensity={0.8} />
      <spotLight
        intensity={1.5}
        angle={0.6}
        penumbra={0.5}
        position={[0, 10, 0]}
        castShadow
        shadow-bias={-0.0001}
      />

      {/* Scene */}
      <Model />
    </>
  )
}

function Loader() {
  const { progress } = useProgress()
  return (
    <Html className='flex items-center justify-center text-2xl'>{progress} % loaded</Html>
  )
}

const animation = {
  display: { opacity: 1, y: 0 },
  hidden: { opacity: 0 }
}

export default function Home() {

  const [open, setOpen] = useState(false)

  return (
    <div className="relative h-screen">
      <Head>
        <title>FreeCar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Canvas shadows>
        <Suspense fallback={<Loader />}>
          <Scene />
        </Suspense>
      </Canvas>

      {/* Présentation de la voiture */}
      <motion.div 
        className='absolute top-10 left-0 right-0 flex flex-col items-center justify-center text-center gap-y-5'
        initial={{
          opacity: 0,
          y: -500
        }}
        animate={ open ? "hidden" : "display"}
        transition={{ duration: 2 }}
        variants={animation}
      >
        <h1 className='text-5xl -mb-3'>Ferrari F40-LM (Le Mans 1985)</h1>
        <span className='text-8xl text-[#B50011] font-bold tracking-wide'>Supercar GT</span>
        <span className='text-3xl'>Découvrez cette magnifique voiture de sport : Ferrari F40</span>
      </motion.div>
      <div className='-z-10 absolute top-[80px] left-0 right-0 flex items-center justify-center text-center'>
        <span className='text-[140px] text-[#f5f5f5] font-bold uppercase tracking-widest'>Ferrari F40-LM</span>
      </div>

      {/* Description de la voiture */}
      <motion.div
        className='absolute bottom-[100px] left-0 right-0 flex items-center justify-between mx-60 text-left'
        initial={{
          opacity: 0,
          y: 500
        }}
        animate={ open ? "hidden" : "display"}
        transition={{ duration: 2 }}
        variants={animation}
      >
        <div>
          <span className='descriptionTitle'>Vitesse Max</span>
          <p className='text-4xl text-[#B50011]'>324<span className='text-xl text-black pl-2'>KM/S</span></p>
        </div>
        <div>
          <span className='descriptionTitle'>Type</span>
          <p className='text-4xl text-[#B50011]'>Supercar GT</p>
        </div>
        <div>
          <span className='descriptionTitle'>Prix à la sortie</span>
          <p className='text-4xl text-[#B50011]'>1 000 000 €</p>
        </div>
        <div>
          <span className='descriptionTitle'>Energie</span>
          <p className='text-4xl text-[#B50011]'>Essence</p>
        </div>
        <div>
          <span className='descriptionTitle'>Chevaux</span>
          <p className='text-4xl text-[#B50011]'>478<span className='text-xl text-black pl-2'>ch</span></p>
        </div>
      </motion.div>

      <div
        className='absolute top-10 right-10'
        onClick={() => setOpen(!open)}
      >
        <AiOutlineInfoCircle fontSize={40} />
      </div>
    </div>
  )
}
